opt_in_rules:
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - prohibited_super_call
  - explicit_init
disabled_rules:
  - file_length
  - force_cast
  - function_body_length
  - line_length
  - todo
  - type_body_length
  - identifier_name
  - type_name
  - function_parameter_count
