disabled_rules: # rule identifiers to exclude from running
  - file_length
  - force_cast
  - function_body_length
  - line_length
  - todo
  - type_body_length
  - variable_name
  - type_name
  - function_parameter_count
