disabled_rules: # rule identifiers to exclude from running
  - file_length
  - force_cast
  - function_body_length
  - line_length
  - todo
  - type_body_length
  - variable_name
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - Source
excluded: # paths to ignore during linting. overridden by `included`.