platform :ios, '8.0'
use_frameworks!

target 'ChattoApp' do
	pod 'Chatto', :path => ".."
	pod 'ChattoAdditions', :path => ".."
end


post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'ChattoAdditions'&& config.name == 'Release'
        # workaround for https://bugs.swift.org/browse/SR-2223
				config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
      end
      
      # Set Swift 2.3 version (Xcode 8)
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
